config:
  kills:
    format:
    - "&8&c&l&x&6&0&f&f&0&0T&x&6&1&f&4&0&0O&x&6&2&d&1&2&0P &x&6&3&b&8&4&0K&x&6&4&a&6&5&0I&x&6&5&9&3&6&0L&x&6&6&7&0&7&0L&x&6&7&6&d&8&0S&8"
    - "&8&6&l1. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l2. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l3. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l4. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l5. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l6. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l7. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l8. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l9. &r&b%player% &7- &e%kills%&8"
    - "&8&6&l10. &r&b%player% &7- &e%kills%&8"
    default: 
    - "&8&c&l&x&6&0&f&f&0&0T&x&6&1&f&4&0&0O&x&6&2&d&1&2&0P &x&6&3&b&8&4&0K&x&6&4&a&6&5&0I&x&6&5&9&3&6&0L&x&6&6&7&0&7&0L&x&6&7&6&d&8&0S&8"
    - "&8&6&l1. Puesto Disponible &8"
    - "&8&6&l2. Puesto Disponible &8"
    - "&8&6&l3. Puesto Disponible &8"
    - "&8&6&l4. Puesto Disponible &8"
    - "&8&6&l5. Puesto Disponible &8"
    - "&8&6&l6. Puesto Disponible &8"
    - "&8&6&l7. Puesto Disponible &8"
    - "&8&6&l8. Puesto Disponible &8"
    - "&8&6&l9. Puesto Disponible &8"
    - "&8&6&l10. Puesto Disponible &8"
  horas:
    format:
    - "&8&c&l&x&6&0&f&f&0&0T&x&6&1&f&4&0&0O&x&6&2&d&1&2&0P &x&6&3&b&8&4&0H&x&6&4&a&6&5&0O&x&6&5&9&3&6&0R&x&6&6&7&0&7&0A&x&6&7&6&d&8&0S&8"
    - "&8&6&l1. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l2. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l3. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l4. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l5. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l6. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l7. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l8. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l9. &r&b%player% &7- &e%horas%&8"
    - "&8&6&l10. &r&b%player% &7- &e%horas%&8"
    default: 
    - "&8&c&l&x&6&0&f&f&0&0T&x&6&1&f&4&0&0O&x&6&2&d&1&2&0P &x&6&3&b&8&4&0H&x&6&4&a&6&5&0O&x&6&5&9&3&6&0R&x&6&6&7&0&7&0A&x&6&7&6&d&8&0S&8"
    - "&8&6&l1. Puesto Disponible &8"
    - "&8&6&l2. Puesto Disponible &8"
    - "&8&6&l3. Puesto Disponible &8"
    - "&8&6&l4. Puesto Disponible &8"
    - "&8&6&l5. Puesto Disponible &8"
    - "&8&6&l6. Puesto Disponible &8"
    - "&8&6&l7. Puesto Disponible &8"
    - "&8&6&l8. Puesto Disponible &8"
    - "&8&6&l9. Puesto Disponible &8"
    - "&8&6&l10. Puesto Disponible &8"
  bloques:
    format:
    - "&8&c&l&x&6&0&f&f&0&0T&x&6&1&f&4&0&0O&x&6&2&d&1&2&0P &x&6&3&b&8&4&0B&x&6&4&a&6&5&0L&x&6&5&9&3&6&0O&x&6&6&7&0&7&0Q&x&6&7&6&d&8&0U&x&6&8&6&8&0E&x&6&9&7&4&8&0S &x&7&0&6&0&8&0M&x&7&1&4&d&9&0I&x&7&2&3&a&n&0A&x&7&3&2&7&d&0D&x&7&4&1&4&o&0S&8"
    - "&8&6&l1. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l2. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l3. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l4. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l5. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l6. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l7. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l8. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l9. &r&b%player% &7- &e%bloques%&8"
    - "&8&6&l10. &r&b%player% &7- &e%bloques%&8"
    default: 
    - "&8&c&l&x&6&0&f&f&0&0T&x&6&1&f&4&0&0O&x&6&2&d&1&2&0P &x&6&3&b&8&4&0B&x&6&4&a&6&5&0L&x&6&5&9&3&6&0O&x&6&6&7&0&7&0Q&x&6&7&6&d&8&0U&x&6&8&6&8&0E&x&6&9&7&4&8&0S &x&7&0&6&0&8&0M&x&7&1&4&d&9&0I&x&7&2&3&a&n&0A&x&7&3&2&7&d&0D&x&7&4&1&4&o&0S&8"
    - "&8&6&l1. Puesto Disponible &8"
    - "&8&6&l2. Puesto Disponible &8"
    - "&8&6&l3. Puesto Disponible &8"
    - "&8&6&l4. Puesto Disponible &8"
    - "&8&6&l5. Puesto Disponible &8"
    - "&8&6&l6. Puesto Disponible &8"
    - "&8&6&l7. Puesto Disponible &8"
    - "&8&6&l8. Puesto Disponible &8"
    - "&8&6&l9. Puesto Disponible &8"
    - "&8&6&l10. Puesto Disponible &8"
message:
  help:
    - "HELP GUI"
    - "/createTopKills(ctk) (String)name (double)height"
    - "/createTopHoras(cth) (String)name (double)height"
    - "/createTopBloques(ctb) (String)name (double)height"
    - "/removeTopData(rtd) (String)type (String)name"
    - "/listTopData(ltd)"
    - "/configTopData(cftd) help"
    - "/configTopData(cftd) reload"
    - "/configTopData(cftd) TopData reload"
    - "/configTopData(cftd) Hologram reload"
    - "/configTopData(cftd) REMOVEARMORSTAND"
  execute:
    correct: "&f¡El comando &b&l%command% &fse ejecuto correctamente!"
    incorrect: "&c¡El comando &b&l%command% &cse ejecuto incorrectamente!"
    no_permission: "&c¡No tienes permiso para ejecutar el comando &b&l%command% !"